### ISSUE TITLE
Boolean radio button options not being internationalized

### ISSUE THREAD

**Issue by jfine** [plataformatec/simple_form#1275]
I have the following form...
```ruby
<%= simple_form_for @exchange_rule do |f| %>
  <%= f.input :publishable, as: :radio_buttons %>
<% end %>
```
...and the following simple_form.yml but it doesn't work...
```yaml
en:
  simple_form:
    options:
      exchange_rule:
        publishable:
          'yes': 'YEP'
          'no': 'NOPE'
```
...when I change simple_form.yml to the following it works...
```yaml
en:
  simple_form:
    'yes': 'YEP'
    'no': 'NOPE'
```
I'd like to target this specific model and attribute. What am I doing wrong?
