### ISSUE TITLE
hint for existing record is not diplayed

### ISSUE THREAD

**Issue by zeke** [plataformatec/simple_form#1344]
``` yml
hints:
  user:
    new:
      invitation_code: "You will eventually need one of these."
    edit:
      invitation_code: "You still need one of these."
```

The `new` hint is displayed for new User records, but no hint is displayed for existing Users. For the time being, I am specifying `:hint` explicitly in the view to work around this.

Are `new` and `edit` only supported for `label`?
