### ISSUE TITLE
Add controller to input translation

### ISSUE THREAD

**Issue by leonelgalan** [plataformatec/simple_form#1464]
Currently it is possible to customize the translation to be used based on the action. This is [done](https://github.com/plataformatec/simple_form/blob/v3.4.0/lib/simple_form/inputs/base.rb#L173), by asking the builder for its [`lookup_action`](https://github.com/plataformatec/simple_form/blob/v3.4.0/lib/simple_form/form_builder.rb#L448), which get's the controller action's name and runs it through a [simple mapping](https://github.com/plataformatec/simple_form/blob/v3.4.0/lib/simple_form/form_builder.rb#L10) to map `'create' => 'new'` and `'update' => 'edit'` and configuring the locales:

In my case, `Notification` is a general purpose way of notifying users about different things and has different delivery mechanisms: in-app message, email, push notifications. So **my labels, placeholders and hints might differ depending on the controller the form is being rendered**. Often the show action of this controllers also includes a `@notification` to render a form in the footer. 

```yaml
en:
  simple_form:
    hints:
      notification:
        new:
          title: This is the subject of the message sent to the user.
```

## Solutions
I'm proposing two different ways to accomplish this. I would like to hear feedback on the desirability of the feature and the feasibility of the proposed solutions. I'm inclining for B, and might start a PR soon as a proof of concept.

### A. Include Controller in the Lookup

```yaml
en:
  simple_form:
    hints:
      notification:
        # Additions:
        'activities#show':
          title: This is the content of the Push Notification received by the user.
        'photos#show':
          title: This would be the subject of the email received by the user
```

When rendering _activities#show_ ideally this looks the entire controller/action pair, before falling back to the action or to the defaults:

* `notification.activities#show.title`
* `notification.show.title`
* `notification.title`

### B. Pass an option to the form to "namespace" the lookup further:

```yaml
en:
  simple_form:
    hints:
      notification:
        # Additions:
        email:
          title: This is the content of the Push Notification received by the user.
```

```ruby
# Inside photos#show
simple_form_for @notification, lookup: 'email' do |f|
  # ...
end
```

Ideally this looks for the custom lookup first, before falling back to the action and the defaults:

* `notification.email.title`
* `notification.show.title`
* `notification.title`
